version: "3.8"

volumes:
  postgres-data:
  pgadmin-data:

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    profiles: ["tools"]
    image: dpage/pgadmin4
    ports:
      - "9201:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.localdomain
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_DISABLE_POSTFIX: "true"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - pgadmin-data:/var/lib/pgadmin
